### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by wsproviero** [dmarron/virdetect#3]
Hello,

I am trying to use a custom Virus.fa.
I am experiencing the following error thrown at me when I lunch the following command:
"java -Xmx4G -cp makeAlignedBed.jar makeAlignedBed STAR_Aligned.out.sam aligned.bed"

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at makeAlignedBed.main(makeAlignedBed.java:25)

(java version "1.8.0_191")

And also this other problem:

"java -Xmx4G -cp picard-1.92.jar:sam-1.92.jar:countStarViralAlignments.jar countStarViralAlignments sample_name STAR_virus_Aligned.out.sam viralReadCounts.txt # 8 G memory"

Exception in thread "main" java.lang.UnsupportedClassVersionError: countStarViralAlignments : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:326)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

Could you please help me understand what I am doing wrong?
Thank you in advance.

William

**Comment by dmarron** [comment]
Hi William,

For the first issue, try running the command java -Xmx4G -cp makeAlignedBed.jar makeAlignedBed STAR_Aligned.out.sam aligned.bed custom_virus.fa.  I think there was a recently introduced typo in the manual that left out custom_virus.fa from the command.

For the second issue, generally the Unsupported major.minor version 52.0 error means that you are running a different java version than the virdetect code was compiled in (which was version 1.8).  However, you state earlier in your message that you are also using java 1.8, so that is a bit confusing.  Could you confirm with java -version that it indeed states 1.8 right before you run the countStarViralAlignments command that gives you that error?  If it does, what I would suggest is recompiling that command with javac from the source code provided in the github in the java/java-src folder.  This will make a .class file which can you run from instead of using the .jar file, and that should guarantee that you won't get a version mismatch error.
I think that it is also odd that you get this error when running countStarViralAlignments.jar but not when you ran makeAlignedBed.jar above, since they are both compiled with the same java version.  Are you using the same java for both commands?
